# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '16.0'

target 'ContractInterface' do
  use_frameworks!
  pod 'web3swift', '~> 3.1.2'
  pod 'XDC3Swift'
end