# Uncomment the next line to define a global platform for your project

name: CIML
source 'https://github.com/CoinClubQuincy/Contract_Interface_Model_Language'
platform: ios, macos
dependencies:
  - web3swift
  - XDC3Swift

target 'ContractInterface' do
  use_frameworks!
  pod 'web3swift', '~> 3.1.2'
  pod 'XDC3Swift'


end